Add Firebase package and Class to do the DB calls
ErwanLBP/java-android-calculIt pull request #20
Opened 2017-07-02 10:52 UTC by ErwanLBP

2017-07-03 20:26 UTC, AlexVcht requested changes

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +        intent.putExtra(User.USER_HIGH_SCORE_HARD, user.getHighScoreHard());
On peut mettre un ticket dessus : https://stackoverflow.com/questions/2139134/how-to-send-an-object-from-one-android-activity-to-another-using-intents 
C'est pour passer un objet et pas 36 trucs un par un, ca demande un peu de taff par contre

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
>                  launchGame(null);
C'est moche d'envoyer null il nous faut une fonction qui initialise proprement ça

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintHighScoresActivity.java
> +                textViewName.setText(Difficulty.MEDIUM.toString());
Name c'était plutot le pseudo de l'utilisateur, si on l'utilise pour la difficulté faut renommer la variable mais comme ca va bouger avec firebase peut etre a la prochaine PR

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintHighScoresActivity.java
> +//        String pseudo = intent.getStringExtra(User.USER_PSEUDO);
Pourquoi tu boycott le pseudo ?

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintResultsActivity.java
> +        setResult(ActivityCode.RC_NEXT_LEVEL);
Pas de nouvel Intent ? On attend pas partout des results ?

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/UserActivity.java
> +        findViewById(R.id.disconnect_button).setOnClickListener(this);
Pour moi sign_out et disconnect c'est la même, de mémoire c'est disconnect qui te détruit de la base : il faudrai un nom plus explicite

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/activity/UserActivity.java
> +        setResult(RESULT_OK);
Intent intent = new Intent();
setResult(RESULT_OK, intent);

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/firebase/FirebaseDB.java
> + * Created by eisti on 01/07/17.
Met tout sauf eisti stp leur donne pas ce mérite :'(

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/firebase/FirebaseDB.java
> +        database.setValue("COUCOU");
C'est laissé exprès le test mdr ?

2017-07-03 20:26 UTC, Alex1664 commented on app/src/main/java/com/erwanlbp/calculit/model/User.java
> +public class User {
Demain inchallah je check project lombok et tous ces getter setter disparaissent 👍

2017-07-04 17:21 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +        intent.putExtra(User.USER_HIGH_SCORE_HARD, user.getHighScoreHard());
Le probleme c'est qu'on veut pas envoyer tout le user... :/ 
Mais ca sera une solution quand on aura des gros objets :+1:

2017-07-04 17:22 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintHighScoresActivity.java
> +//        String pseudo = intent.getStringExtra(User.USER_PSEUDO);
Pour l'instant on en a pas besoin, elle va pas mal changer cette activity, je voulais juste que ca marche

2017-07-04 17:24 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintHighScoresActivity.java
> +                textViewName.setText(Difficulty.MEDIUM.toString());
changed

2017-07-04 17:25 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/PrintResultsActivity.java
> +        setResult(ActivityCode.RC_NEXT_LEVEL);
il faut recreer une config et tout, et puis je sais pas je prefere pas trop faire une longue chaine d'intent nan ?

2017-07-04 17:32 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/UserActivity.java
> +        setResult(RESULT_OK);
pourquoi envoyer un intent vide?

2017-07-04 17:39 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/firebase/FirebaseDB.java
> +        database.setValue("COUCOU");
ouai pour voir comment ca marche,

2017-07-04 17:54 UTC, merged