Feature/level
ErwanLBP/java-android-calculIt pull request #6
Opened 2017-06-28 20:32 UTC by Alex1664

2017-06-28 21:11 UTC, ErwanLBP commented on app/build.gradle
> +    productFlavors {
remove

2017-06-28 21:12 UTC, ErwanLBP commented on app/build.gradle
> +    }
Remove productFlavors { }

2017-06-28 21:14 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/ActivityCode.java
> +    public final static int DIFFICULTY = value++;
Plutôt SELECT_DIFFICULTY, comme ton activity s'appelle SelectDifficultyActivity

2017-06-28 21:17 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +    public static final int CONFIG_DEFAULT_DIFFICULTY = 1000;
= Difficulty.EASY.getTimeToPrint()

2017-06-28 21:19 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +        this(CONFIG_DEFAULT_SIZE, difficulty.getValue(), CONFIG_DEFAULT_MAX_NUMBER, difficulty);
difficulty.getTimeToPrint()

2017-06-28 21:36 UTC, erwanlbp requested changes
La majorité des review c'est des trucs qui vont etre modifié suite à un changement de nom de fonction tkt

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +    public static final int CONFIG_DEFAULT_SIZE = 5;
Vaut mieux commencer plus facile nan? Genre 2, ca c'est facile

2017-06-28 21:36 UTC, ErwanLBP commented on app/build.gradle
> +    }
Remove productFlavors { }

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/ActivityCode.java
> +    public final static int DIFFICULTY = value++;
Plutôt SELECT_DIFFICULTY, comme ton activity s'appelle SelectDifficultyActivity

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +    public static final int CONFIG_DEFAULT_DIFFICULTY = 1000;
= Difficulty.EASY.getTimeToPrint()

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +        this(CONFIG_DEFAULT_SIZE, difficulty.getValue(), CONFIG_DEFAULT_MAX_NUMBER, difficulty);
2e argument : difficulty.getTimeToPrint()

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/GameConfig.java
> +    private GameConfig(final int n, final int timeToPrint, final int maxNumber, Difficulty difficulty) {
C'est redondant de recevoir timeToPrint et difficulty, c'est la meme chose au final.
Enleve le timeToPrint, et met this.timeToPrint=difficulty.GetTimeToPrint()

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +public class DifficultyActivity extends AppCompatActivity {
Plutot SelectDifficultyActivity

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +    public void chooseDifficulty(final View view) {
pas de final ici, le prototype d'un onClick doit etre 'public void <nom>(View view)'
le view est pas constant

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +                intent.putExtra(DIFFICULTY, Difficulty.EASY.getValue());
getTimeToPrint()

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +                intent.putExtra(DIFFICULTY, Difficulty.MEDIUM.getValue());
Same

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +                intent.putExtra(DIFFICULTY, Difficulty.HARD.getValue());
Same

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +                intent.putExtra(DIFFICULTY, Difficulty.GOD.getValue());
Same

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/DifficultyActivity.java
> +            default: intent.putExtra(DIFFICULTY, Difficulty.EASY.getValue());
Same

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/Enum/Difficulty.java
> +    GOD(500);
2000 pour easy, c'est compliqué à 1000
1200
800
400

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/Enum/Difficulty.java
> +    public int getValue() {
getTimeToPrint

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/Enum/Difficulty.java
> +    public static Difficulty parse(final int difficulty) {
On aura pas besoin de cette fonction, supprime là pour le moment stp

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +    protected void onCreate(final Bundle savedInstanceState) {
pas de final ici stp, pas sur les Override

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +        final Intent intent = new Intent(this, GameActivity.class);
Pas de final ici, on va lui mettre des extras ! c'est pas une constante !

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +    public void selectDifficulty(final View view) {
pas de final

2017-06-28 21:36 UTC, ErwanLBP commented on app/src/main/java/com/erwanlbp/calculit/activity/MainActivity.java
> +        final Intent intent = new Intent(this, DifficultyActivity.class);
SelectDifficultyActivity

2017-06-29 18:46 UTC, erwanlbp approved these changes

2017-06-29 18:46 UTC, merged